# Generated by Django 5.0 on 2023-12-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="grupo_sanguineo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("B+", "B+"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
