# Generated by Django 5.0 on 2023-12-15 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_paciente_telefono_clinica_clinicamiembro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinica",
            name="user",
        ),
    ]
