# Generated by Django 5.0 on 2023-12-21 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_categoriadiagnostico_diagnostico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnostico",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.categoriadiagnostico",
            ),
        ),
        migrations.CreateModel(
            name="DiagnosticoPaciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comentario", models.TextField()),
                (
                    "diagnostico",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.categoriadiagnostico",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
