# Generated by Django 5.0 on 2023-12-21 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_diagnostico_categoria_diagnosticopaciente"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticopaciente",
            name="paciente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.paciente",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosticopaciente",
            name="comentario",
            field=models.TextField(blank=True, null=True),
        ),
    ]
